name: Build Android AAB with Expo EAS

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Log in to Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Android AAB
        run: eas build -p android --profile production --non-interactive

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: |
            dist/*.aab
            ./*.aab
            **/*.aab